# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "node-runtime-serve-static"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
#confirm_changeset = true
confirm_changeset = false
resolve_s3 = true
#resolve_image_repos = true
#s3_bucket = "node-runtime-serve-static-bucket"
region = "ap-southeast-1"
image_repositories = []
stack_name = "node-runtime-serve-static"
s3_prefix = "node-runtime-serve-static"
disable_rollback = true
parameter_overrides = "StageName=\"$default\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
