AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Nuxt 3 Serverless SSR in AWS
Parameters:
  DomainName:
    Type: String
    Description: Domian name for api
    Default: 'internal-poc.appmanteam.com'
  StageName:
    Type: String
    Default: $default

Resources:
  ExpressApi:
    Type: AWS::Serverless::HttpApi
  # "s3BucketName": "sls-xpress-edge1",
  ExpressLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      MemorySize: 1024
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExpressApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NodeNextApi:
    Description: API Gateway endpoint URL for default stage for Node Next function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/default/'
  NuxtDemoFunction:
    Description: Nuxt Demo Lambda Function ARN
    Value: !GetAtt NuxtDemoFunction.Arn
  NuxtDemoFunctionIamRole:
    Description: Implicit IAM Role created for Nuxt Demo function
    Value: !GetAtt NuxtDemoFunctionRole.Arn
