AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: The AWS CloudFormation template for this Serverless application
Resources:
  NodeServeStaticLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/node-runtime-serve-static
  NodeServeStaticFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      FunctionName: node-runtime-serve-static
      MemorySize: 1024
      Timeout: 6
      Environment:
        Variables:
          NODE_ENV: dev
      Events:
        EntryPoint:
          Type: Api
          Properties:
            Path: /
            Method: get
        EntryPointProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    DependsOn:
      - NodeServeStaticLogGroup